const messages = {
    tr: {
        loading: 'Yükleniyor...',
        adminTitle: 'NISSAI Yönetici Paneli',
        adminSubtitle: 'Asistan, sektör ve operasyon ayarlarını buradan yönetin.',
        saveSuccess: 'Ayarlar kaydedildi.',
        resetSuccess: 'Ayarlar varsayılan değerlere döndürüldü.',
        fetchConfigError: 'Ayarlar alınamadı.',
        saveError: 'Ayarlar kaydedilemedi.',
        resetError: 'Ayarlar sıfırlanamadı.',
        assistantName: 'Asistan Adı',
        systemPrompt: 'Sistem Promptu',
        welcomeMessage: 'Karşılama Mesajı',
        primaryColor: 'Ana Renk',
        provider: 'Sağlayıcı',
        baseUrl: 'Servis Adresi',
        apiKey: 'API Anahtarı (Opsiyonel)',
        model: 'Model',
        temperature: 'Sıcaklık',
        sectorKey: 'Sektör Anahtarı',
        landingVariant: 'Landing Varyantı',
        assistantRole: 'Asistan Rolü',
        ctaTarget: 'CTA Hedefi',
        theme: 'Tema',
        enabled: 'Asistan Aktif',
        save: 'Kaydet',
        reset: 'Sıfırla',
        chatTitleSuffix: 'Mesaj Merkezi',
        userMessage: 'Mesajınız',
        send: 'Gönder',
        assistantReply: 'Asistan Yanıtı',
        chatError: 'Yanıt alınamadı.',
        notAuthorized: 'Bu ekran için önce giriş yapmalısınız.',
        landingHeadline: 'Dağınıklığı bitir, operasyonunu tek panelden yönet.',
        landingSubheadline: 'Hızlı kurulum, net kontrol ve ölçülebilir sonuç için yönetici girişinden devam edin.',
        loginTitle: 'Yönetici Girişi',
        loginSubtitle: 'Yalnız yetkili kullanıcılar ayar paneline erişebilir.',
        loginUsername: 'Kullanıcı Adı',
        loginPassword: 'Parola',
        loginButton: 'Yönetici Girişi',
        loginError: 'Giriş bilgileri doğrulanamadı.',
        logout: 'Çıkış Yap',
        sectorShowcaseTitle: 'Sektöre göre çalışma senaryoları',
        sectorShowcaseSubtitle: '14 sektör altyapısı hazır. İlk yayında yalnızca avukatlar sayfası aktif.',
        sectorOpen: 'Sayfayı Aç',
        sectorSoon: 'Yakında',
        lawyersLink: 'Avukat asistanı sayfasını aç'
    },
    en: {
        loading: 'Loading...',
        adminTitle: 'NISSAI Admin Panel',
        adminSubtitle: 'Manage assistant, sector, and operations settings here.',
        saveSuccess: 'Settings saved.',
        resetSuccess: 'Settings restored to defaults.',
        fetchConfigError: 'Failed to fetch settings.',
        saveError: 'Failed to save settings.',
        resetError: 'Failed to reset settings.',
        assistantName: 'Assistant Name',
        systemPrompt: 'System Prompt',
        welcomeMessage: 'Welcome Message',
        primaryColor: 'Primary Color',
        provider: 'Provider',
        baseUrl: 'Service URL',
        apiKey: 'API Key (Optional)',
        model: 'Model',
        temperature: 'Temperature',
        sectorKey: 'Sector Key',
        landingVariant: 'Landing Variant',
        assistantRole: 'Assistant Role',
        ctaTarget: 'CTA Target',
        theme: 'Theme',
        enabled: 'Assistant Enabled',
        save: 'Save',
        reset: 'Reset',
        chatTitleSuffix: 'Message Center',
        userMessage: 'Your Message',
        send: 'Send',
        assistantReply: 'Assistant Response',
        chatError: 'Failed to get response.',
        notAuthorized: 'You need to sign in first.',
        landingHeadline: 'End operational chaos and manage from one control panel.',
        landingSubheadline: 'Continue through admin sign-in for faster setup and clearer control.',
        loginTitle: 'Admin Sign In',
        loginSubtitle: 'Only authorized users can access the settings panel.',
        loginUsername: 'Username',
        loginPassword: 'Password',
        loginButton: 'Admin Sign In',
        loginError: 'Unable to validate credentials.',
        logout: 'Sign Out',
        sectorShowcaseTitle: 'Industry operating scenarios',
        sectorShowcaseSubtitle: 'Infrastructure for 14 sectors is ready. Only lawyers is active in first release.',
        sectorOpen: 'Open Page',
        sectorSoon: 'Coming Soon',
        lawyersLink: 'Open lawyers assistant page'
    }
}

export const getWixooLiteTexts = () => {
    const forcedLang = typeof window !== 'undefined' ? new URLSearchParams(window.location.search).get('lang')?.toLowerCase() : null
    const locale = forcedLang === 'en' ? 'en' : 'tr'
    return messages[locale]
}
